---
title: "Gov 50 Final Project"
author: "Richie Mamam Nbiba"
description: "Using R to describe the relationship between wealth disparities and mortality rates in regards of health care access."
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...

Question: How does a lack of democracy impact a certain country’s death rates?
If an African country has a lower average democracy then the country’s death rate will be higher because of corrupt killings. My explanatory variable is average government democracy. Average Government democracy seems to be measured from 0 through 10 which measures a country’s democracy based on the democracy index which is developed on 60 Indicators of 5 different categories. My Outcome Variable is Death PC which measures deaths per capita in a given country. Observed patterns in the data would provide support for my hypothesis are if there is if lower democracy scores on average had increased Death PC rates.  An observed pattern that would disprove my hypothesis is if the relationship between death rates and democracy scores is not inverse. 

```{r}
library(tidyverse)
violence<- read_csv(file="violence.csv")
ate_corruption <- violence |>
  filter(africa == 1) |>
  summarize(africa, corrupti, sftgname, agovdem80, assass80, code, deathsPC80, democ70, deathsPC70, na.rm=TRUE) |>
 mutate(Corruption=  if_else( corrupti <= 5, 
           "more_corrupt", "less_corrupt"),
        Democracy= if_else(democ70 >= 5, "Democratic", "Authoritarian"))
ate_corruption

corrupt_graph <- ate_corruption |>
ggplot(mapping = aes(x = democ70 , y = corrupti)) +
geom_col()

corrupt_graph

death_table<-ate_corruption|>
  group_by(Democracy)|>
  summarise(Mean_death= mean(deathsPC70, na.rm=TRUE))|>
  pivot_wider(names_from = Democracy,
values_from = Mean_death) |>
  mutate(ATE= `Authoritarian` - `Democratic`) 

death_table |>
  select(-"NA")

knitr::kable(death_table, 
             col.names = c("Democratic Death Rate", "Authoritarian Death Rate", "NA", "ATE"),
             digits = 3) 
```

This table represents the respective death rates for african countries that are democratic vs african countries that are authoritarian in the 70's. The death rate for countries that are authoritarian was significantly less than democraic countries. This could be because in "democratic" countries their is more accurate death reports of death rates due to more social freedom. 

